### ISSUE TITLE
Star/Watch Override

### ISSUE THREAD

**Issue by cpholguera** [OWASP/www-project-mobile-security-testing-guide#36]
Consider overriding the Star/Watch of the website with the ones from the MSTG

According to this:

https://github.com/OWASP/www--site-theme/issues/8#issuecomment-546987233

![Screenshot at 2019-11-16 16-02-30](https://user-images.githubusercontent.com/29175115/68992013-c0590500-0865-11ea-9f7f-1562e07e7ef5.png)

**Comment by commjoen** [comment]
@hblankenship can you help us out with this? @sushi2k & @cpholguera maybe it is ok if people can just use it to wath the site. but then it should be clear that you are watching this repo, not the projects repo itself :D
